let handler  = async (m, { conn }) => {
conn.reply(m.chat,`*┌────「 DESAFIO 」─*\n*“${pickRandom(global.bucin)}”*\n*└────「 HERCULES 」─*`, m)
}
handler.help = ['desafio']
handler.tags = ['fun']
handler.command = /^desafio/i
export default handler

function pickRandom(list) {
  return list[Math.floor(list.length * Math.random())]
}

global.bucin = [
  "Passe o pacote de uma formiga",
  "Diga aos seus amigos que você vai morar nos EUA e me envie uma captura de tela do que eles te disserem",
  "Grite pela janela que você quer chupar e me envie o vídeo",
  "Escreva o nome do seu crush",
  "Você deve colocar o nome do meu criador no seu status do WhatsApp, sem dar contexto",
  "Envie uma foto sua",
  "Você deve desenhar em alguma parte do seu corpo o nome de algum membro do grupo, depois tire uma foto e envie",
  "Tire uma foto beijando uma televisão",
  "Me envie uma foto de roupa íntima",
  "Escreva no seu status do WhatsApp que você gosta de comer terra",
  "Você deve colocar a foto de um participante do grupo do sexo oposto ao seu em seu perfil do WhatsApp por 3 dias 📸📸",
  "Você precisa enviar um áudio cantando a música: Um pato que vai cantando alegremente cua cua 🦆",
  "Envie uma mensagem para o seu ex dizendo que ainda gosta dele(a)",
  "Envie um áudio dizendo amo a The Hercules Bot",
  "Diga ao seu crush que o ,ama e envie uma captura de tela para o grupo",
  "Envie um áudio cantando",
  "Envie uma foto sua sem cobrir o rosto ou qualquer coisa do tipo",
  "Envie um vídeo dançando",
  "Convide pessoas que você não conhece para tirar uma selfie com você e depois envie para o grupo",
  "Escolha alguns números aleatórios dos seus contatos e envie uma mensagem de texto com a frase 'Estou grávida'.",
  "Pegue qualquer bebida que estiver perto de você, depois misture com pimenta e beba!",
  "Pegue um número aleatório dos seus contatos, ligue para ele e diga 'eu te amo'",
  "Compre a comida mais barata na cantina (ou compre uma garrafa de água) e diga soluçando para os seus colegas de classe: 'Esta... é a comida mais cara que eu comprei)'",
  "Compre uma garrafa de Coca-Cola e jogue flores com ela na multidão",
  "Fique em pé perto da geladeira, feche os olhos, escolha alimentos aleatórios lá dentro e mesmo quando estiver comendo, seus olhos devem estar fechados",
  "Fique no meio da quadra de basquete e grite 'EU TE AMO MEU PRÍNCIPE/PRINCESA'",
  "Apresente seus respeitos a alguém da classe e diga: 'Estou ao seu serviço, Majestade'",
  "Ande batendo palmas e cantando a música 'Feliz Aniversário' pela sala de aula",
  "Ajoelhe-se em um joelho e diga 'Você quer se casar comigo?' para a primeira pessoa que entrar na sala",
  "Crie um acessório absurdo com tecido, seja o que for, continue fazendo poses na frente da câmera, continue postando",
  "Diga 'VOCÊ É LINDA/MUITO LINDA, NÃO MENTE' para a garota que você acha a mais bonita da sala",
  "Diga para alguém da classe: 'Primeiro me disseram que éramos gêmeos, nos separamos e depois fiz uma cirurgia plástica. E isso é a coisa mais séria que eu já disse'",
  "Jogue o caderno de alguém no lixo, na frente dos olhos deles, dizendo 'Este livro ninguém pode entender'",
  "Arranque três fios de cabelo da sua própria perna!",
  "Converse com seus pais, diga que está com saudades deles usando emojis tristes",
  "Tente pesquisar no Google coisas assustadoras ou ridículas, como tripofobia, etc.",
  "Sente-se relaxado no meio da quadra de basquete fingindo que é uma praia para tomar sol",
  "Encha a boca de água e tente segurar por duas rodadas, se você rir e derramar ou beber, então você precisa encher de novo e adicionar mais uma rodada",
  "Cumprimente a primeira pessoa que entrar na sala e diga 'Bem-vindo ao Quem Quer Ser um Milionário!'",
  "Envie uma mensagem para seus pais dizendo 'Oi, irmão! Acabei de comprar a última edição da revista Playboy!'",
  "Envie uma mensagem para seus pais dizendo 'Mamãe, papai, eu sei que sou adotado do orfanato. Não esconda mais isso'.",
  "Envie três números aleatórios da sua lista de contatos e escreva 'Acabei de me tornar modelo da revista Playboy'",
  "Tome uma colher de molho de soja doce e molho de soja!",
  "Coma algo, mas não use as mãos",
  "Fique bravo com seus amigos que não aparecem mesmo tendo um compromisso para jogar 'Verdade ou Desafio' juntos",
  "Quebre o ovo com a cabeça!",
  "Coma alimentos que estejam misturados e tenham um sabor estranho, mas certifique-se de que não sejam prejudiciais à saúde a curto ou longo prazo",
  "Dance como o Girls' Generation para os meninos na frente da sala, ou dance como o Super Junior para as meninas",
  "Içar o mastro da bandeira sem a bandeira",
  "Fale sobre a pessoa que você gosta, seus amigos mais próximos, pessoas do sexo oposto que você não conhece e coisas do tipo",
  "Copie os penteados de todos os seus amigos",
  "Cante a música HAI TAYO na frente de muitas pessoas enquanto dança",
  "Cante a música Baby Shark em voz alta na sala de aula",
  "Pegue algo emprestado dos vizinhos",
  "Peça a assinatura de um dos professores mais rigorosos enquanto diz 'Você é verdadeiramente a pessoa que mais admiro no mundo'",
  "Peça dinheiro a alguém (aleatório) na rua dizendo 'Não tenho dinheiro para pegar um ônibus'",
  "Beba algo que tenha sido preparado/acordado, mas certifique-se de que não seja perigoso. Pode ser como beber xarope misturado com molho de soja",
  "Converse com a pessoa que você gosta usando o emoji de medo, está tudo bem conversar sobre o que quiser, por qualquer meio que você possa",
  "Cante a sua música favorita da Disney do lado de fora de casa enquanto grita",
  "Conte de 1 a 20 rapidamente, nomeando uma cor azul para cada número, e não cometa nenhum erro. Se errar, deve começar de novo",
  "Coloque uma coroa de papel e diga para todos na sala 'HONRA AO REI', apontando para cada pessoa com uma régua",
  "Vista novamente as calças até a manhã seguinte",
  "Abrace a pessoa da sala que você não gosta e diga 'Muito obrigado por ser a melhor pessoa para mim'",
  "Vá para um campo aberto e corra o mais rápido possível enquanto diz 'Estou louco, estou louco'",
  "Escolha uma flor e dê para alguém que você não conhece (deve ser do sexo oposto)",
  "Escolha uma pessoa aleatória na rua e diga 'Você não sabe que é linda?' (como o One Direction)",
  "Fingir estar possuído, por exemplo, possuído por um tigre, etc.",
  "Peça para a pessoa assobiar, já que a boca dela está cheia de comida novamente",
  "Passear como garçom para servir você e seus amigos no almoço",
  "Peça para eles usarem meias como luvas",
  "Peça para eles usarem o chapéu mais estranho/o capacete mais absurdo na próxima rodada",
  "Ligue para sua mãe e diga 'Mãe, quero me casar o mais rápido possível'",
  "Ligue para o seu ex e diga 'sinto sua falta'",
  "Troque de roupa com a pessoa mais próxima até a próxima rodada",
  "Atualize seu status no WhatsApp com o que quiser, usando palavras que comecem com a letra 'S'",
  "Faça upload de um vídeo cantando no YouTube, onde você canta músicas populares",
  "Pinte suas unhas das mãos e dos pés com cores diferentes por uma semana",
  "Coma 2 colheres de arroz sem acompanhamentos",
  "Envie o emoji '🦄💨' sempre que escrever em um grupo por 1 dia",
  "Diga 'Bem-vindo ao Quem Quer Ser um Milionário!' para todos os grupos que você tem",
  "Canta o refrão da última música que você tocou", 
] 
